class Language {
  String name;
  String code;
  bool isRecent;
  bool isDownloaded;
  bool isDownloadable;

  Language(String code, String name, bool isRecent, bool isDownloaded,
      bool isDownloadable) {
    this.name = name;
    this.code = code;
    this.isRecent = isRecent;
    this.isDownloaded = isDownloaded;
    this.isDownloadable = isDownloadable;
  }

  static List<Language> getLanguages() {
    return <Language>[
      Language('af', 'Afrikaans', false, false, true),
      Language('sq', 'Albanian', false, false, true),
      Language('am', 'Amharic', false, false, false),
      Language('ar', 'Arabic', false, false, true),
      Language('hy', 'Armenian', false, false, false),
      Language('az', 'Azerbaijani', false, false, false),
      Language('eu', 'Basque', false, false, false),
      Language('be', 'Belarusian', false, false, true),
      Language('bn', 'Bengali', false, false, true),
      Language('bs', 'Bosnian', false, false, false),
      Language('bg', 'Bulgarian', false, false, true),
      Language('ca', 'Catalan', false, false, true),
      Language('ceb', 'Cebuano', false, false, false),
      Language('ny', 'Chichewa', false, false, false),
      Language('zh-cn', 'Chinese Simplified', true, false, true),
      Language('zh-tw', 'Chinese Traditional', false, false, true),
      Language('co', 'Corsican', false, false, false),
      Language('hr', 'Croatian', false, false, true),
      Language('cs', 'Czech', false, false, true),
      Language('da', 'Danish', false, false, true),
      Language('nl', 'Dutch', false, false, true),
      Language('en', 'English', true, true, true),
      Language('eo', 'Esperanto', false, false, true),
      Language('et', 'Estonian', false, false, true),
      Language('tl', 'Filipino', false, false, true),
      Language('fi', 'Finnish', false, false, true),
      Language('fr', 'French', true, true, true),
      Language('fy', 'Frisian', false, false, false),
      Language('gl', 'Galician', false, false, true),
      Language('ka', 'Georgian', false, false, true),
      Language('de', 'German', false, false, true),
      Language('el', 'Greek', false, false, true),
      Language('gu', 'Gujarati', false, false, true),
      Language('ht', 'Haitian Creole', false, false, true),
      Language('ha', 'Hausa', false, false, false),
      Language('haw', 'Hawaiian', false, false, false),
      Language('iw', 'Hebrew', false, false, true),
      Language('hi', 'Hindi', false, false, true),
      Language('hmn', 'Hmong', false, false, false),
      Language('hu', 'Hungarian', false, false, true),
      Language('is', 'Icelandic', false, false, true),
      Language('ig', 'Igbo', false, false, false),
      Language('id', 'Indonesian', false, false, true),
      Language('ga', 'Irish', false, false, true),
      Language('it', 'Italian', false, false, true),
      Language('ja', 'Japanese', false, false, false),
      Language('jw', 'Javanese', false, false, true),
      Language('kn', 'Kannada', false, false, true),
      Language('kk', 'Kazakh', false, false, false),
      Language('km', 'Khmer', false, false, false),
      Language('ko', 'Korean', false, false, true),
      Language('ku', 'Kurdish (Kurmanji)', false, false, false),
      Language('ky', 'Kyrgyz', false, false, false),
      Language('lo', 'Lao', false, false, false),
      Language('la', 'Latin', false, false, false),
      Language('lv', 'Latvian', false, false, true),
      Language('lt', 'Lithuanian', false, false, true),
      Language('lb', 'Luxembourgish', false, false, false),
      Language('mk', 'Macedonian', false, false, true),
      Language('mg', 'Malagasy', false, false, false),
      Language('ms', 'Malay', false, false, true),
      Language('ml', 'Malayalam', false, false, false),
      Language('mt', 'Maltese', false, false, true),
      Language('mi', 'Maori', false, false, false),
      Language('mr', 'Marathi', false, false, true),
      Language('mn', 'Mongolian', false, false, false),
      Language('my', 'Myanmar (Burmese)', false, false, false),
      Language('ne', 'Nepali', false, false, false),
      Language('no', 'Norwegian', false, false, true),
      Language('ps', 'Pashto', false, false, false),
      Language('fa', 'Persian', false, false, true),
      Language('pl', 'Polish', false, false, true),
      Language('pt', 'Portuguese', false, false, true),
      Language('ma', 'Punjabi', false, false, false),
      Language('ro', 'Romanian', false, false, true),
      Language('ru', 'Russian', false, false, true),
      Language('sm', 'Samoan', false, false, false),
      Language('gd', 'Scots Gaelic', false, false, false),
      Language('sr', 'Serbian', false, false, false),
      Language('st', 'Sesotho', false, false, false),
      Language('sn', 'Shona', false, false, false),
      Language('sd', 'Sindhi', false, false, false),
      Language('si', 'Sinhala', false, false, false),
      Language('sk', 'Slovak', false, false, true),
      Language('sl', 'Slovenian', false, false, true),
      Language('so', 'Somali', false, false, false),
      Language('es', 'Spanish', false, false, true),
      Language('su', 'Sundanese', false, false, false),
      Language('sw', 'Swahili', false, false, true),
      Language('sv', 'Swedish', false, false, true),
      Language('tg', 'Tajik', false, false, false),
      Language('ta', 'Tamil', false, false, true),
      Language('te', 'Telugu', false, false, true),
      Language('th', 'Thai', false, false, true),
      Language('tr', 'Turkish', false, false, true),
      Language('uk', 'Ukrainian', false, false, true),
      Language('ur', 'Urdu', false, false, true),
      Language('uz', 'Uzbek', false, false, false),
      Language('vi', 'Vietnamese', false, false, true),
      Language('cy', 'Welsh', false, false, true),
      Language('xh', 'Xhosa', false, false, false),
      Language('yi', 'Yiddish', false, false, false),
      Language('yo', 'Yoruba', false, false, false),
      Language('zu', 'Zulu', false, false, false),
    ];
  }
}
